name: ArxivLearner
options:
  bundleIdPrefix: com.arxivlearner
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  groupSortPosition: top
settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
targets:
  ArxivLearner:
    type: application
    platform: iOS
    sources:
      - path: ArxivLearner
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arxivlearner.app
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: ArxivLearner/Info.plist
      properties:
        CFBundleDisplayName: ArxivLearner
        UILaunchScreen: {}
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
  ArxivLearnerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ArxivLearnerTests
    dependencies:
      - target: ArxivLearner
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arxivlearner.tests
