name: ArxivLearner
options:
  bundleIdPrefix: com.arxivlearner
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  groupSortPosition: top
settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
targets:
  ArxivLearner:
    type: application
    platform: iOS
    sources:
      - path: ArxivLearner
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arxivlearner.app
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: ArxivLearner/ArxivLearner.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.arxivlearner.app
        com.apple.developer.icloud-services:
          - CloudDocuments
          - CloudKit
        com.apple.developer.ubiquity-container-identifiers:
          - iCloud.com.arxivlearner.app
        aps-environment: development
    info:
      path: ArxivLearner/Info.plist
      properties:
        CFBundleDisplayName: ArxivLearner
        UILaunchScreen: {}
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIBackgroundModes:
          - fetch
          - remote-notification
          - processing
        BGTaskSchedulerPermittedIdentifiers:
          - com.arxivlearner.refresh
  ArxivLearnerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ArxivLearnerTests
    dependencies:
      - target: ArxivLearner
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arxivlearner.tests
        GENERATE_INFOPLIST_FILE: YES
  ArxivLearnerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: ArxivLearnerUITests
    dependencies:
      - target: ArxivLearner
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arxivlearner.uitests
        GENERATE_INFOPLIST_FILE: YES
